### ISSUE TITLE
sp_conf

### ISSUE THREAD

**Issue by jvazquez** [CZ-NIC/pyoidc#50]
Roland,

Sorry, could you provide an example of sp_conf.py for op2 ?
This is related with issue #43 

``` bash
Traceback (most recent call last):
  File "server.py", line 479, in <module>
    "%s/authorization" % config.issuer, userinfo=config.USERINFO)
  File "/home/jvazquez/env/forkpyoidc/local/lib/python2.7/site-packages/oic/utils/authn/saml.py", line 72, in __init__
    self.sp_conf = importlib.import_module(spconf)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named sp_conf
```

**Comment by herchila** [comment]
Roland,

Sorry, but... where is the stripped down version of config.py that you normally use?

In op2 I see two config files: config.py.simple and config.py.full and when I run `python server.py -p 8092 -d config`, return this: 

`ImportError: No module named sp_conf`
